const sources = [
  'index.html',
  'manifest.json',
  'sw.js',
  'app/app.js',
  'app/errorHandlers.js',

  'app/fetching.js',
  'app/handleSubmit.js',
  'app/inputHandlers.js',
  'app/navigate.js',
  'app/styleChangers.js',
  'app/touchIF.js',
  'app/variable.js',

  'app/generateHTML/genBottom.js',
  'app/generateHTML/genDefenitions.js',
  'app/generateHTML/genEverything.js',
  'app/generateHTML/genMeaning.js',
  'app/generateHTML/genPhonetAudio.js',
  'app/generateHTML/genSyn.js',
  'app/generateHTML/removeHtml.js',

  'styles/styles.css',
  'assets/images/arrow-up-right-from-square-solid.svg',
  'assets/images/logo32x32.png',
  'assets/images/logo.svg',
  'assets/images/icon-arrow-down.svg',
  'assets/images/icon-moon-dark.svg',
  'assets/images/icon-moon.svg',
  'assets/images/icon-new-window.svg',
  'assets/images/icon-play.svg',
  'assets/images/icon-search.svg',
  'assets/images/xmark-red.svg',
  'assets/images/xmark.svg',
  'assets/fonts/IBMPlexMono/IBMPlexMono-Bold.ttf',
  'assets/fonts/IBMPlexMono/IBMPlexMono-BoldItalic.ttf',
  'assets/fonts/IBMPlexMono/IBMPlexMono-Regular.ttf',
  'assets/fonts/inter/Inter-VariableFont_slnt,wght.ttf',
  'assets/fonts/lora/Lora-VariableFont_wght.ttf',
];
export { sources };
